name 'net35'
maintainer 'Timothy Wright'
maintainer_email 'chef@eastbound.io'
license 'Apache-2.0'
description 'Installs/Configures net35'
long_description 'Installs/Configures net35'
version '0.1.0'
chef_version '>= 13.0'
